const SERVICES = [
  // Santé & Médecine
  "Médecin généraliste",
  "Médecin spécialiste",
  "Pédiatre",
  "Gynécologue",
  "Cardiologue",
  "Dermatologue",
  "Ophtalmologue",
  "ORL",
  "Réflexologue",
  "Psychiatre",
  "Dentiste",
  "Orthodontiste",
  "Chirurgien dentiste",
  "Kinésithérapeute",
  "Ostéopathe",
  "Chiropracteur",
  "Psychologue",
  "Psychothérapeute",
  "Infirmier / Infirmière",
  "Sage-femme",
  "Podologue",
  "Orthophoniste",
  "Orthoptiste",
  "Opticien",
  "Diététicien / Nutritionniste",
  "Acupuncteur",
  "Naturopathe",
  "Homéopathe",
  "Sophrologue",
  "Hypnothérapeute",
  "Ergothérapeute",
  "Psychomotricien",
  "Neurologue",
  "Rhumatologue",
  "Gastroentérologue",
  "Endocrinologue",
  "Angiologue",
  "Chirurgien",
  "Radiologue",
  "Urologue",
  "Pneumologue",
  "Oncologue",
  "Allergologue",
  "Médecin du sport",
  "Médecin esthétique",
  "Sexologue",
  "Gériatre",
  // Beauté & Bien-être
  "Coiffeur / Coiffeuse",
  "Barbier",
  "Esthéticienne",
  "Manucure / Prothésiste ongulaire",
  "Pédicure",
  "Maquilleur / Maquilleuse",
  "Tatoueur / Tatoueuse",
  "Pierceur",
  "Masseur / Masseuse",
  "Spa & Centre de bien-être",
  "Institut de beauté",
  "Centre d'épilation laser",
  "Microblading & Sourcils",
  "Extension de cils",
  "Bronzage UV",
  // Sport & Fitness
  "Coach sportif / Personal trainer",
  "Salle de sport",
  "Professeur de yoga",
  "Professeur de pilates",
  "Professeur de danse",
  "Professeur de natation",
  "Professeur d'arts martiaux",
  "Professeur de boxe",
  "Professeur de tennis",
  "Professeur de golf",
  "Préparateur physique",
  "Professeur de crossfit",
  // Automobile & Mécanique
  "Garagiste / Mécanicien auto",
  "Carrossier",
  "Contrôle technique",
  "Électricien automobile",
  "Pneumaticien",
  "Mécanicien moto",
  // Bâtiment & Habitat
  "Architecte",
  "Décorateur d'intérieur",
  "Électricien",
  "Plombier",
  "Charpentier",
  "Menuisier",
  "Peintre en bâtiment",
  "Maçon",
  "Serrurier",
  "Vitrier",
  "Jardinier / Paysagiste",
  "Carreleur",
  "Chauffagiste",
  "Climaticien",
  // Juridique & Finance
  "Avocat",
  "Notaire",
  "Expert-comptable",
  "Conseiller financier",
  "Gestionnaire de patrimoine",
  "Huissier de justice",
  "Médiateur",
  "Conseiller juridique",
  // Conseil & Coaching
  "Coach de vie / Life coach",
  "Coach business",
  "Consultant",
  "Consultant RH",
  "Consultant marketing",
  "Formateur professionnel",
  "Thérapeute de couple",
  "Conseiller en orientation",
  // Éducation & Formation
  "Professeur particulier",
  "Tuteur",
  "Professeur de musique",
  "Professeur de piano",
  "Professeur de guitare",
  "Professeur de langues",
  "Auto-école",
  // Animaux
  "Vétérinaire",
  "Toiletteur pour animaux",
  "Éducateur canin",
  "Pet sitter",
  // Photo & Événementiel
  "Photographe",
  "Vidéaste",
  "DJ",
  "Traiteur",
  "Organisateur d'événements",
  "Wedding planner",
  "Animateur / Magicien",
  // IT & Tech
  "Développeur freelance",
  "Consultant IT",
  "Réparateur informatique",
  "Réparateur de téléphone",
  "Designer graphique",
  "Designer UX/UI",
  // Immobilier
  "Agent immobilier",
  "Gestionnaire de biens",
  "Chasseur immobilier",
  // Services à la personne
  "Aide à domicile",
  "Baby-sitter",
  "Garde d'enfants",
  "Auxiliaire de vie",
  "Aide-soignant",
  // Autre
  "Autre",
];

module.exports = SERVICES;
